# pubspec.yaml

name: oncredit
description: "Aplicativo Dart & Flutter para controle de pagamentos fiados."
publish_to: 'none'
version: 2026.01.001+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.1
  intl: ^0.19.0
  mask_text_input_formatter: ^2.5.0
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.2
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"
