# pubspec.yaml

name: oncredit
description: "Aplicativo Dart & Flutter para controle de pagamentos fiados."
publish_to: 'none'
version: 2026.01.30

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.1

  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
